var myPlaylist = [
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4TFB1X0ZkNlBieDA',
		oga:'#',
		title:'broken hearted woman',
		artist:'Vương Phi (Faye Wong)',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TFB1X0ZkNlBieDA',
		price:'0',
		duration:'05:18',
		cover:'https://www.mediafire.com/convkey/efc1/wuus14ornmq2i9w6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4R3lwLVZOVjZVOU0',
		oga:'#',
		title:'caravan of life',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4R3lwLVZOVjZVOU0',
		price:'0',
		duration:'03:40',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eVF4VmhUNXBfQ3c',
		oga:'#',
		title:'circle in the sand',
		artist:'Belinda Carlisle',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eVF4VmhUNXBfQ3c',
		price:'0',
		duration:'03:41',
		cover:'https://www.mediafire.com/convkey/fac7/1rbqujgf9m7bbgo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eTM1dnJmSDR0eE0',
		oga:'#',
		title:'coco jambo',
		artist:'Mr President',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eTM1dnJmSDR0eE0',
		price:'0',
		duration:'03:43',
		cover:'https://www.mediafire.com/convkey/7fa7/4wvcgxk8o3loayi6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4VUFCQzVrRzc3NFE',
		oga:'#',
		title:'iam so in love with u',
		artist:'Jill Andrews',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VUFCQzVrRzc3NFE',
		price:'0',
		duration:'04:32',
		cover:'https://www.mediafire.com/convkey/e201/cv7fwc7tbmiqp736g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4b3BmN2lNeEZXYzA',
		oga:'#',
		title:'keep on loving u',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4b3BmN2lNeEZXYzA',
		price:'0',
		duration:'04:05',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RC1mcjVCbHNuRUU',
		oga:'#',
		title:'lonely',
		artist:'Akon',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RC1mcjVCbHNuRUU',
		price:'0',
		duration:'04:08',
		cover:'https://www.mediafire.com/convkey/0a37/6jxdaav0k79kaqj6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RGw3WWVlWGR5b28',
		oga:'#',
		title:'memories of u',
		artist:'Chinese Melody',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RGw3WWVlWGR5b28',
		price:'0',
		duration:'03:50',
		cover:'https://www.mediafire.com/convkey/585a/tjsux0cffuvvpu96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bFE4NWh1bVFpMWs',
		oga:'#',
		title:'miss u not',
		artist:'Chinese Melody',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bFE4NWh1bVFpMWs',
		price:'0',
		duration:'03:47',
		cover:'https://www.mediafire.com/convkey/585a/tjsux0cffuvvpu96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=1oyFP16pp6rLmDazc9hxJVMA5c0dBhWS5',
		oga:'#',
		title:'moon light',
		artist:'L.L Kiệt (Jet Li)',
		rating:5,
		buy:'https://drive.google.com/open?id=1oyFP16pp6rLmDazc9hxJVMA5c0dBhWS5',
		price:'0',
		duration:'03:56',
		cover:'https://www.mediafire.com/convkey/cfd6/qra2m4kc11pyy1w6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=1IleufLxLYxgXY7AtkfCkRmMkEQn3jUg4',
		oga:'#',
		title:'no face no name no num',
		artist:'Modern Talking',
		rating:5,
		buy:'https://drive.google.com/open?id=1IleufLxLYxgXY7AtkfCkRmMkEQn3jUg4',
		price:'0',
		duration:'03:57',
		cover:'https://www.mediafire.com/convkey/0708/25ag5tzsldp8osm6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4elJ4dmhjekxGZ00',
		oga:'#',
		title:'sad without u',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4elJ4dmhjekxGZ00',
		price:'0',
		duration:'04:23',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RkEzZEZtWjJBcnM',
		oga:'#',
		title:'say that u love me',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RkEzZEZtWjJBcnM',
		price:'0',
		duration:'03:46',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4LUNCMjM5c3BNdlE',
		oga:'#',
		title:'self control',
		artist:'Laura Branigan',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4LUNCMjM5c3BNdlE',
		price:'0',
		duration:'03:39',
		cover:'https://www.mediafire.com/convkey/40c1/p69mcxzw3blkjs66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RXZtYVQ1eDhvaW8',
		oga:'#',
		title:'sexy sexy lover',
		artist:'Modern Talking',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RXZtYVQ1eDhvaW8',
		price:'0',
		duration:'03:02',
		cover:'https://www.mediafire.com/convkey/0708/25ag5tzsldp8osm6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UFpfbFVPY0tfUm8',
		oga:'#',
		title:'that is love',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UFpfbFVPY0tfUm8',
		price:'0',
		duration:'04:06',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RmhrWHZaV0U0U28',
		oga:'#',
		title:'till the end of time',
		artist:'Chinese Melody',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RmhrWHZaV0U0U28',
		price:'0',
		duration:'04:27',
		cover:'https://www.mediafire.com/convkey/585a/tjsux0cffuvvpu96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Z2MxckVENnN2ajA',
		oga:'#',
		title:'tokyo by night',
		artist:'Gina T',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Z2MxckVENnN2ajA',
		price:'0',
		duration:'03:46',
		cover:'https://www.mediafire.com/convkey/ec0b/qke8qbeyxb8wwge6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bGpLTzVmcnItNVU',
		oga:'#',
		title:'tomorrow will come',
		artist:'Chinese Melody',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bGpLTzVmcnItNVU',
		price:'0',
		duration:'03:47',
		cover:'https://www.mediafire.com/convkey/585a/tjsux0cffuvvpu96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4S0lTcjdWQzJTd00',
		oga:'#',
		title:'walking in the sun',
		artist:'Degauss',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4S0lTcjdWQzJTd00',
		price:'0',
		duration:'05:44',
		cover:'https://www.mediafire.com/convkey/585a/tjsux0cffuvvpu96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bW9WUkQzSGQ5cGc',
		oga:'#',
		title:'what is love',
		artist:'Haddaway',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bW9WUkQzSGQ5cGc',
		price:'0',
		duration:'04:29',
		cover:'https://www.mediafire.com/convkey/911b/4vywqhlmapyoevl6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Y3RWbzgtTTNJUDQ',
		oga:'#',
		title:'within u will remain',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Y3RWbzgtTTNJUDQ',
		price:'0',
		duration:'03:58',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4YUZBci1yZVBaNVE',
		oga:'#',
		title:'u will find your way',
		artist:'Tokyo Square',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4YUZBci1yZVBaNVE',
		price:'0',
		duration:'02:21',
		cover:'https://www.mediafire.com/convkey/738b/6i55tnkf6rkgjy86g.jpg'
	}
];
